platform :ios, '6.0' 
#pod 'SHOmniAuth',	  :git => "http://github.com/seivan/SHOmniAuth", :branch => :develop
pod 'SHOmniAuthFacebook', :path => '../'
pod 'SHActionSheetBlocks'
pod 'SHAlertViewBlocks'
pod 'SHFastEnumerationProtocols'